<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
xmlns="http://www.w3.org/1999/xhtml"
xmlns:doc="http://www.xqdoc.org/1.0"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:fn="http://www.w3.org/2005/02/xpath-functions"
xmlns:c="http://www.w3.org/ns/xproc-step"
exclude-result-prefixes="xs doc fn"
version="2.0">

<xsl:output method="html" indent="yes" encoding="UTF-8"/>
<xsl:param name="source" as="xs:string"/>

  <!-- generate module html //-->
  <xsl:template match="/">
    <html>
      <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta http-equiv="Generator" content="xquerydoc - https://github.com/xquery/xquerydoc" />
	<title>xqDoc - </title>
        <style type="text/css">
	body,
	html {
	margin:0;
	padding:0;
	color:#000;
	background:#a7a09a;
	}
	#wrap {
	width:100%;
        height:100%;
	margin:0 auto;
	background:#99c;
	}
	#header {
    	padding:5px 10px;
	background:#ddd;
	}
	h1 {
	margin:0;
            }
	#main {
	float:right;
	width:75%;
	padding:0px;
	background:#9c9;
        overflow:auto;
	}
	h2 {
	margin:0 0 1em;
	}
	#sidebar {
        float:left;
	width:25%;
	padding:0px;
	background:#99c;
        overflow:auto;
	}
	#footer {
	clear:both;
	padding:5px 10px;
	background:#cc9;
	}
	#footer p {
	margin:0;
        }
	* html #footer {
	height:1px;
	}
        </style>
	<link rel="stylesheet" type="text/css" href="lib/prettify.css">&#160;</link>
	<script src="lib/prettify.js" type="lib/javascript">&#160; </script>
	<script src="lib/lang-xq.js" type="text/javascript">&#160; </script>
      </head>
      <body>
        <div id="wrap">
          <div id="header">
            <h1>docs</h1>
          </div>
          <div id="sidebar">
            <ul>
              <xsl:apply-templates select="//*:file"/>
            </ul>
          </div>
          <div id="main">
          <iframe name="docs" style="height:100%;width:100%"/>
          </div>
          <div id="footer">
              <i>
                <xsl:value-of select="()"/>
                </i> |
                generated by xquerydoc <a
                href="https://github.com/xquery/xquerydoc"
                target="xquerydoc">https://github.com/xquery/xquerydoc</a>
          </div>
        </div>
	<script type="application/javascript">
	  window.onload = function(){ prettyPrint(); }
	</script>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="*:file">
    <li><a href="{@gname}.html" target="docs"><xsl:value-of select="@base"/>/<xsl:value-of select="@name"/></a></li>
  </xsl:template>

</xsl:stylesheet>
