#!/bin/bash

# Copyright (c) 2011-2012 Jim Fuller, John Snelson  
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0
  
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# xquerydoc 0.1, generates xquery api documentation
#
# see https://github.com/xquery/xquerydoc
#
# usage: xquerydoc [-x xquery directory] [-o output directory ] [-f output format ]
#


CURRENTDIR=`pwd`

#Edit these default values
#####################################################################
XQUERY=$CURRENTDIR
OUTPUT=$CURRENTDIR/xqdoc
XQUERY=$CURRENTDIR
FORMAT=html
#####################################################################

function usage(){
    echo "xquerydoc 0.1, generates xquery api documentation"
    echo "Copyright (c) 2011, 2012 Jim Fuller, John Snelson"
    echo "see https://github.com/xquery/xquerydoc"
    echo ""
    echo "usage: xquerydoc [-x xquery directory] [-o output directory ] [-f output format ]"
    echo ""

    exit 1
}

while getopts 'x:o:f:h' OPTION
do
case $OPTION in
    x) XQUERY="$OPTARG";;
    o) OUTPUT="$OPTARG";;
    f) FORMAT="$OPTARG";;
    *)
      usage
      exit 1;;
  esac
done

echo "xquerydoc procesing ..."
echo ""
echo "xquery: $XQUERY"
echo "output: $OUTPUT"
echo "format: $FORMAT"
echo ""

# run xproc pipeline
deps/xmlcalabash/calabash -oresult=$OUTPUT/index.html xquerydoc.xpl xquery=$XQUERY output=$OUTPUT currentdir=$CURRENTDIR format=$FORMAT 

# copy lib resources
mkdir -p $OUTPUT/lib
cp src/lib/prettify.js $OUTPUT/lib/prettify.js
cp src/lib/prettify.css $OUTPUT/lib/prettify.css
cp src/lib/lang-xq.js $OUTPUT/lib/lang-xq.js

exit
